### ISSUE TITLE
Isomorphic / universal rendering

### ISSUE THREAD

**Issue by anaibol** [planttheidea/remeasure#3]
H! Thanks for this package!
I was asking me if it's supports rendering outside the browser, since there is no `window` object on node. The solution should be to do it on `componentDidMount` maybe?

**Comment by planttheidea** [comment]
Hi @anaibol! I can certainly try to rework it so that access to window is done dynamically on first attempt rather than statically on load. The only place that happens is in the coalescing for requestAnimationFrame (for vendor fallbacks).

Now that said, I'm not sure it would resolve the issue, because I'm fairly certain with a universal app `componentDidMount` will fire prior to the browser being present. I'll try this simple fix, and if that doesn't work then I'll probably have to ask for a PR (because I'm inexperienced with universal apps).

**Comment by anaibol** [comment]
I am fairly sure that  `componentDidMount` runs on the browser, even on universal apps!
See https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount

**Comment by planttheidea** [comment]
Rock on, I'm just finishing up the change for this now.

**Comment by planttheidea** [comment]
Alright @anaibol I have release 1.2.1, which abstracts the assignment of `raf` to a `setRaf` function that is only called on `componentDidMount` if `raf` is not already assigned. Let me know if this solves your issue.

**Comment by planttheidea** [comment]
Since I didn't get a response, I forked [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) and applied measure to a few components in there, everything seemed to work out of the box without any errors. As a result, I'm calling this closed, but @anaibol if you continue having issue let me know and I'm happy to work with you to resolve it.

**Comment by anaibol** [comment]
Hi, sorry for the late answer. I tried it on a stateless component and it worked as expected, getting `0` values on the server rendering and getting the right values on the client.

Thanks!

```javascript
export default connect(
  state => ({ unreadMessages: state.message.unread })
)(measure(({ unreadMessages, position, size }) => {
  console.log(position);
  console.log(size);
  return (
    <div className={s.nav}>
      <Link className={s.link} icon="home" text="Home" to="/" hideText />
      <Link className={s.link} icon="map-marker" text="Explore" to="/explore" hideText />
      <Link className={s.link} icon="circled-user-male" text="Profile" to="user" hideText>
        <Badge num={2} />
      </Link>
      <Link className={s.link} icon="speech" text="Messages" to="messages" hideText>
        <Badge num={unreadMessages.length} />
      </Link>
    </div>
  )
}))
```
