### ISSUE TITLE
How do you share props with parent?

### ISSUE THREAD

**Issue by adamsoffer** [planttheidea/remeasure#35]
This is a great library, thanks! I was wondering - is there are a way to share a measured component's props with a parent component? Basically, I need access to a child's width. I need a resize function on `Measure` or something where I could set state.

**Comment by Sigfried** [comment]
What's the distinction you're making? For my use case, I want to keep parents (actually, siblings) in sync. Also, the coordinates I would like to keep track of are for the center of the element, relative to  the containing <g> element in an <svg>. (Specifically, I want to draw links between nodes in a graph; so a link with references to its source and target will draw itself from the center of the source to the center of the target.) If the library currently works with svg elements, getting the center shouldn't be hard, but can you confirm whether it does? 

A handy convenience feature would allow the user to add new measurements that can be calculated from existing measurements but can be accessed and monitored in the same way.

I haven't tried it yet, but it looks great! Thanks!

**Comment by planttheidea** [comment]
I haven't tested this out with SVG elements, but internally it uses getBoundingClientRect and native properties like offset top, so I don't see why it wouldn't.

I'm a bit confused by the second statement ... Do you mean add properties that can be measured, in addition to what is already measured? Because the available options are intended to be a complete list, if something is missing let me know and I can add it.
